### ISSUE TITLE
Change the default exchange type to topic

### ISSUE THREAD

**Issue by micdenny** [mizrael/OpenSleigh#10]
https://github.com/mizrael/OpenSleigh/blob/100e40afe09fdd89d81bc4e162fe94f50c789be6/src/OpenSleigh.Transport.RabbitMQ/PublisherChannelFactory.cs#L29

Would be great to support more exchange type, like the most powerful one `topic`, but probably could be more convenient to stick on `topic` as default, and expose the ability to let the user decide the topic to use when publish, and from consuming perspective let the user decide which topic to use when binding to the exchange (with a default to `#`).

What do you think?

**Comment by mizrael** [comment]
This is the next area I'm going to focus on. Ideally, the exchange type depends on the type of message, be it a command or an event. Commands are meant to be received by a single consumer (expecially if it is scaled horizontally).
Events, on the other hand, are meant to be broadcasted to all the subscribed consumers.

I still have to come up with the proper design, might take a while.

**Comment by mizrael** [comment]
code updated in https://github.com/mizrael/OpenSleigh/pull/15
