### ISSUE TITLE
Support for batch child sagas

### ISSUE THREAD

**Issue by izzycoding** [mizrael/OpenSleigh#18]
I guess this is more of a question...

Is it possible for a saga to send multiple messages for child sagas and then only continue once all the child sagas are completed?

Currently I think this would require manual tracking of child sagas in the parent and only “publishing” the continuation message once all children completed messages have been received.

This is be cause I have a distributed process that is capable of running multiple parts at the same time and then merges the results. If I had to do this one at a time then my “saga” could take days to complete instead of minutes/hours.

it would be good to have something like this supported natively in the framework.

**Comment by mizrael** [comment]
hi @izzycoding , thanks for the question! I think you're close with your idea. One option would be to publish a "completed" event every time a child Saga completes. You can then have a parallel "orchestrator" Saga that collects in its state all those events. When all child Sagas are completed, this parallel orchestrator can send a command to the initial "parent" saga to resume its work.
What do you think?

**Comment by izzycoding** [comment]
So my “orchestrator” saga would map to an IEvent of StartChildProcessMessage to register the child process and then once all the related Completed events are triggered it then fires the parents continuation?

I think I get it. Will see what I can do as an implementation. I might even be able to provide a generic class to wrap up the mechanism.

**Comment by mizrael** [comment]
more or less. I would suggest having:
- a main parent Saga. This is the first one to be triggered, starts the whole process, and sends the start commands for all the child Sagas.
- N child Sagas. Each one has its own start Command and its own "OnCompleted" event. 
- a sub-orchestrator Saga. This one listens to all the "OnCompleted" events and fires a "resume parent execution" command.

**Comment by izzycoding** [comment]
I assume the sub-orchestrator would also need to listen for or have a trigger to know how many child processes have started? I guess that would just be an IEvent too and the child would send that on start but the IEvent just wouldn’t set the state complete flag.

**Comment by mizrael** [comment]
if the child Sagas have all the same type, then yes, you'd need a way to
keep track of the count.
Otherwise just use different IEvent implementations for each child Saga

Il giorno sab 23 gen 2021 alle ore 12:29 izzycoding <
notifications@github.com> ha scritto:

**Comment by mizrael** [comment]
I guess this can be closed. Let me know if there's anything else
