### ISSUE TITLE
Re-publish with back-off/delay

### ISSUE THREAD

**Issue by izzycoding** [mizrael/OpenSleigh#23]
Possibly another question but...

Is it possible for a handler to re-publish a received message but with a delay?

for example if my Saga has a “polling” step that calls an external service for a ready state, if the external service is not ready can I re-submit the same message but give it a delay so it is not executed before a given timeout?
Also, could that delay be configured to increase for each iteration of the message? E.G. if a service is overloaded then my service will back-off to allow time for it to “catch up”.

Essentially my saga is calling an API I am not in control of. I send a request, then poll until the status is “complete”, then download the results.

**Comment by mizrael** [comment]
you might not need to republish the message at all. Saga handlers don't have the concept of "timeout" (or at least, not yet). I guess one option would be to just poll in a while loop inside your message handler and put a `Task.Delay()` if data is not available from the external service.

**Comment by mizrael** [comment]
closing for now, feel free to reopen if you need more feedback!
