### ISSUE TITLE
A glitch in OpenSleigh.Persistence.SQLServer dependencies

### ISSUE THREAD

**Issue by nicogiard** [mizrael/OpenSleigh#46]
I'm trying to build from scratch a worker, based on the Sample3.Worker. Nothing fancy, just the basics.
I added the NuGets that follows :
- OpenSleigh.Persistence.SQLServer : 1.0.0
- OpenSleigh.Transport.Kafka : 0.3.0

And everything seems to compile, but at runtime, there is an error such as : 
```
Unhandled exception. System.MethodAccessException: Attempt by method 'OpenSleigh.Persistence.SQLServer.SqlBusConfiguratorExtensions.UseSqlServerPersistence(OpenSleigh.Core.DependencyInjection.IBusConfigurator, OpenSleigh.Persistence.SQL.SqlConfiguration)' to access method 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<OpenSleigh.Core.Persistence.ITransactionManager,OpenSleigh.
Persistence.SQL.SqlTransactionManager>(Microsoft.Extensions.DependencyInjection.IServiceCollection)' failed.
```
Another clue, in the DI, when writing the `services.AddOpenSleigh(cfg => ...`, my IDE (Rider) propose both `UseSqlPersistence` and `UseSqlServerPersistence`. Strange isn't it ?

Previously, the `OpenSleigh.Persistence.SQL` project was built and packed as a nuget. The last version was 1.3.1.

With the introduction of PostgreSQL, the `OpenSleigh.Persistence.SQL` was marked as "not packable" (sorry if it's a bad term, this is what i see in Rider).

But the `OpenSleigh.Persistence.SQLServer` project has a reference on `OpenSleigh.Persistence.SQL`, with version 1.0.0, and if i understand well what's going on, i think NuGet retrieve the "old" version 1.0.0 of `OpenSleigh.Persistence.SQL`, not the "new" one. 

In the Samples, everything is project references, so there is no NuGet involved, that's why it's working. Don't you think ?

Maybe if we could rename `OpenSleigh.Persistence.SQL` to `OpenSleigh.Persistence.SQL.Core` in order to not fool NuGet ? Or do you have a better idea to handle this situation ?

**Comment by nicogiard** [comment]
I have created a sample repo on github to illustrate this problem :
https://github.com/nicogiard/OpenSleighWorker

- Open the .sln
- Build is OK
- Launch => the Exception is launched

**Comment by mizrael** [comment]
hi @nicogiard , thanks for pointing this out! There was an issue with release 1.5.0, it was using a previous version of the SQL library, where the `SqlTransactionManager` class was still marked as internal.
I've pushed new versions of the packages, it should be fine now.
