### ISSUE TITLE
'Saga state is already locked' error when processing the last retry.

### ISSUE THREAD

**Issue by sergegommers** [mizrael/OpenSleigh#50]
Hi,

i'm running sample3. I only modified it by adding a retry policy at start up of the worker:

    cfg.AddSaga<SimpleSaga, SimpleSagaState>()
        .UseStateFactory<StartSimpleSaga>(msg => new SimpleSagaState(msg.CorrelationId))
        .UseRabbitMQTransport()
        .UseRetryPolicy<StartSimpleSaga>(builder =>
        {
          builder.WithMaxRetries(5)
              .Handle<ApplicationException>()
              .WithDelay(executionIndex => TimeSpan.FromSeconds(executionIndex))
              .OnException(ctx =>
              {
                System.Console.WriteLine(
                      $"tentative #{ctx.ExecutionIndex} failed: {ctx.Exception.Message}");
              });
        });

In the Saga itself, an exception is thrown:

    public async Task HandleAsync(IMessageContext<StartSimpleSaga> context, CancellationToken cancellationToken = default)
    {
      _logger.LogInformation($"starting saga '{context.Message.CorrelationId}'...");

      throw new ApplicationException("Kaboem");

      var message = new ProcessSimpleSaga(Guid.NewGuid(), context.Message.CorrelationId);
      this.Publish(message);
    }

It does indeed 5 retries, but after the 5th retry this error pops up:

a fatal error has occurred while processing Message '29e95851-8a6f-4f90-9839-f7b0ad0fe90d' from Exchange 'startsimplesaga' : One or more errors occurred. (saga state '0fac261f-3db8-4161-9922-17ad5790cc80' is already locked) . Rejecting...

I would expect it to fail gracefully, and move the message to the dead letter queue.

In fact, removing the retry policy and just throwing an exception in the Saga has the same results.

By the way, thanks for this project, I'm looking for a more lightweight solution then NServicebus that plays nice with .Net Core, and where the Sagas can be installed like plugins. I will certainly continue to evaluate it.

Serge

**Comment by mizrael** [comment]
hi Serge, thanks for reaching out! I've released a new version of the Core and RabbitMQ packages, please let me know if it solves your problem :)

**Comment by sergegommers** [comment]
Hi David. The lock issue is solved indeed, the message eventually goes to the deadletter queue, but, it doesn't go immediately. Without a retry policy, the message is handled twice. With the 5-retries policy the message is handled 10 times.

**Comment by mizrael** [comment]
hi Serge,

yes, that was an implementation choice I took. The RabbitMq driver has this
in-built retry mechanism, in case transient errors occur during elaboration.
I understand this might cause conflicts with the retry policies you're
using, so if you want, I can release another version and make that
configurable.
Let me know what you think

**Comment by sergegommers** [comment]
Hi David. Probably it's better to make that configurable indeed, Suppose someone implements a policy with an exponential delay, you don't expect that the Saga goes through that cycle twice. Also, some exceptions might indicate a non-recoverable error, no need for a retry in this case.
Thanks for following up so quickly.
