### ISSUE TITLE
Non-dead letter queues are set to auto-delete

### ISSUE THREAD

**Issue by sergegommers** [mizrael/OpenSleigh#52]
Hi David,

inside RabbitSubscriber.cs, the non-dead letter queues are set to auto delete.
This means that for your sample3, if the worker is shutdown while handling a message, the queue gets deleted and hence the message is lost. 
Probably it is better to make the auto-delete configurable.

**Comment by mizrael** [comment]
hi Serge, I just pushed a new release, let me know what you think!

https://github.com/mizrael/OpenSleigh/releases/tag/v1.6.2

**Comment by sergegommers** [comment]
Hi David. When shutting down the worker, the queue is now kept. But when starting the worker, it tries to process the message, and fails with error 'saga state x is already locked'. Also the message is removed from the worker queue without it actually having been handled. To reproduce this just set a breakpoint in the SimpleSaga, shut down the worker, and restart it.

I believe you also removed the built-in retry? I can confirm it now works without that retry.

**Comment by mizrael** [comment]
hi Serge,

this is happening because the first worker "locked" the message. The default lock duration is 1 minute but can be changed during bootstrap:

```
var sqlConfig = new SqlConfiguration(sqlConnStr,
                            new SqlSagaStateRepositoryOptions(System.TimeSpan.FromSeconds(10)),
                            SqlOutboxRepositoryOptions.Default);
```

That being said, I can try to update the RabbitSubscriber to re-enqueue a "locked" message, possibly with some configurable delay so that it can be reprocessed by another consumer after some time.

**Comment by mizrael** [comment]
hi Serge,
I've added a delayed retry mechanism on message lock, let me know if it works for you.

Thanks!

**Comment by sergegommers** [comment]
Hi David, thanks, that retry works beautifully.

1 Remark however: Out of the box Sample3 is broken now. To be able to run it I had to add an instance of RabbitConfiguration to the DI container at startup of the worker. I guess that's needed because RabbitSubscriber now depends on RabbitConfiguration.

I created a PR with a more elegant fix.

**Comment by mizrael** [comment]
thank you very much for your help on this, I really appreciate it! I've approved the PR and created a new [release](https://github.com/mizrael/OpenSleigh/releases/tag/v1.6.4).

Thanks!
