### ISSUE TITLE
Can not add custom VirtualHost to RabbitConfiguration

### ISSUE THREAD

**Issue by fissama** [mizrael/OpenSleigh#57]
I try to connect my RabbitMQ server but I have received the issue that VirtualHost from my **UseRabbitMQTransport()** is **"/"** (default) and I can not custom **VirtualHost** in **RabbitConfiguration**. Is there any way to fix this issue?
Many thanks,

**Comment by mizrael** [comment]
hi, I've released a new version, let me know if it fixes your issue: https://github.com/mizrael/OpenSleigh/releases/tag/v2.0.1

thanks!

**Comment by fissama** [comment]
Thanks for your support! It helps a lot with my project.

many thanks,

**Comment by mizrael** [comment]
thanks for using OpenSleigh!
