### ISSUE TITLE
core vs implementation

### ISSUE THREAD

**Issue by seertenedos** [mizrael/OpenSleigh#63]
It would be nice if there was a nuget with zero or very little dependancies that could be added to all the libaries that contain Saga's. Eg just the interfaces and required entities.  Then a seperate one that has the implementation and DI etc. Your current Core one requires DependencyInjection nuget to be added to all my libraries not just my main program exe where the DI actually is. You do it for the transport and persistance just one more to allow Saga's to have minimal references would be nice.

**Comment by mizrael** [comment]
that's an interesting thought. Although it would require one additional nuget per existing package, just to strip out the DI code. 
Usually the dependency is taken once and then inherited on all the dependent assemblies.
Just to clarify, what is the primary concern for not having the DI nuget in your libs?

**Comment by seertenedos** [comment]
It seems to me the sagas and their related types like start messages may need to be shared between projects so may even end up on internal nuget repos etc. The less dependancies you have in projects the less chance of conflict in nuget versions later on.  Also in a lot of those sort of libaries DI etc just does not belong there normally. It belongs at the exe itself where they could use many different types of DI etc. linking it to every dll that has a saga seems over kill. Also i have a core lib in my projects that generally just contains entities and interfaces shared over projects and applications. It generally references very little apart from some abstractions or other interfaces but this would need me to have DI refernce there if i was adding the Start Saga messages there and Completed events so other projects could trigger a saga etc.

For existing projects it would not be a breaking change as the implementation "Core" currentlky could reference this new nuget and then would auto pull it with no change but it would allow others to use the entity/interface nuget in libs if they wanted

**Comment by mizrael** [comment]
unfortunately, there's a lot of bootstrap code done during DI setup, I can't simply remove the dependency.  I see your point, and it's definitely valuable. It would also give support to different IoC libraries. 
However, it's a big breaking change given the status of things right now.

I'll add it to my pipeline and see if I can add it to a future release. Thanks!

**Comment by seertenedos** [comment]
I had a look at the code and the classes need to write Sagas etc for libs seem to be SagaState, Saga, IStartedBy, IHandleMessage, ICommand and IEvent.  Now some of those classes/interfaces need other classes and interfaces but from a quickish look i could not see why all of those classes could not be seperated out into a different nuget that does not need DI references and likely any of the other references on the Core nuget and then the Core nuget could reference this nuget,

Sort of like how in Dotnet you use Microsoft.Extensions.Logging.Abstractions in all your libaries and only use the actual logging implementation where you do the DI on the main EXE if that makes sense.

**Comment by seertenedos** [comment]
Thanks for making the change!
