### ISSUE TITLE
End to End test for multi step saga

### ISSUE THREAD

**Issue by seertenedos** [mizrael/OpenSleigh#70]
I have seen the unit test to test a single step in a Saga but i was wondering if a unit test could be added showing an Start to End of a Saga. I am thinking about how i would easily test the different flows though the Saga and test it correctly handles the compensations when and how i expect it to.

At the minute i just have a 3 step saga and 1 compensation which actually calls another saga as well but happy to subsitute that out. I just want to make sure i understand the ebst way to test these as they become more complex and you need to deal with potential flow issues with the messages etc.

**Comment by mizrael** [comment]
hi @seertenedos, apologies for the late reply. I am thinking a lot about this. Orchestrating E2E tests between multiple services is not an easy feat. I am planning on improving traceability between service calls (eg. a different correlation scheme on messages), but it might take a while.
