### ISSUE TITLE
Question: can opensleigh be used also as pure outbox pattern implementation for message brokers?

### ISSUE THREAD

**Issue by paulvanbladel** [mizrael/OpenSleigh#72]
David,
Very intresting project !
I hope you don't mind i ask a question via this way.
I recently came accross another prety intresting outbox pattern implementation: https://github.com/dotnetcore/CAP
Probably there is kind of overlap but the CAP project is clearly not a saga implementation but the outbox (and inbox) machinery works quite good. (e.g. when you take down the broker, no messages are lost)
OpenSleigh has of course a different scope, but i was wondering if it covers also the stuff CAP is doing?
kind regards
paul

**Comment by mizrael** [comment]
hi Paul, thanks for reaching out! I have personally never used CAP, only heard a bit about it. From what I understand, it's a nice, multi-provider implementation of the Outbox pattern.
OpenSleigh uses the same approach to ensure at-least-once delivery. Messages are appended to a table _before_ being published and then processed by a background worker.
Hope that satisfies your question :)

**Comment by paulvanbladel** [comment]
Hey David,
Thanks a lot for the prompt reply.
Well, I think I better understand now the difference between both libraries.
My 2 cents... :)

**CAP** is a pure application of the outbox pattern but as far as I can see only for **event based communication** (so e.g. when the exchange type is a topic in rabbitmq). It is therefore useful for saga **choreography** (so based on eventing and with an **implicit** state machine spread across the different parties in the saga).

**OpenSleigh** is **command oriented** and therefore suitable for **orchestration** based sagas. So the type of exchange is not event based but more the direct command style communication based on an **explicit** state machine.

All the best.
paul.

**Comment by mizrael** [comment]
hi @paulvanbladel, 
that's correct. The main goal of OpenSleigh is to provide easy-to-use Saga Orchestration. That being said, it can also be used to broadcast events to multiple consumer groups.
