### ISSUE TITLE
Do not force loading of all assemblies

### ISSUE THREAD

**Issue by mxrnx** [mizrael/OpenSleigh#74]
Hi @mizrael, thanks for your work on OpenSleigh!

Since commit [7613a1d](https://github.com/mizrael/OpenSleigh/commit/7613a1dda6c3a7562b7813e008dece47bdc28808), OpenSleigh now overrides the framework's default behavior of lazy loading assemblies by force loading all assemblies when OpenSleigh is injected.

I discovered this because my project failed to start: I had an assembly that was referenced but not actually present (which is a separate problem on my side). More importantly, my startup times have increased by 10-20 seconds, since every assembly is now recursively iterated for all other assemblies it references.

In general, this seems like an antipattern: after all, there's a reason assemblies are lazy loaded, and this might trigger more, unrelated issues.

What is the exact reason OpenSleigh now does things this way, and is there another way to achieve it?

**Comment by mizrael** [comment]
hi @knarka, thanks for reaching out. Apologies for the inconvenience, but unfortunately this is the only reliable way I've found to guarantee message discovery. And trust me, I don't like it either.
I'll try to do some more analysis and see if this can be avoided somehow.

**Comment by mizrael** [comment]
solved in v3.
