### ISSUE TITLE
Avoid create channel per publish

### ISSUE THREAD

**Issue by micdenny** [mizrael/OpenSleigh#9]
https://github.com/mizrael/OpenSleigh/blob/100e40afe09fdd89d81bc4e162fe94f50c789be6/src/OpenSleigh.Transport.RabbitMQ/RabbitPublisher.cs#L33

Connections and Channels are meant to be long-lived, see [Connection and Channel Lifespan](https://www.rabbitmq.com/dotnet-api-guide.html#connection-and-channel-lifspan).

Create a channel per publish can kill throughput in high load scenario, in the other hand having a lot of channels always opened can consume more resources, but with better throughput.

A good compromise and usually [a rule of thumb](https://www.rabbitmq.com/channels.html#resource-usage) is to limit the channels per thread, managing those in a pool where you take care also to recreate channel when and if rabbitmq closes them.

BTW if you want to create a channel every time, then you need to dispose it, and the code doesn't do it, so this it's more a bug to me.

Hope this can help you improve this framework that took my attention for it's simplicity regard to other big framework out there.

**Comment by mizrael** [comment]
hi @micdenny, thank you very much for the advice! I'll review the code and update it as you suggested 👍🏻

**Comment by mizrael** [comment]
@micdenny 
https://github.com/mizrael/OpenSleigh/blob/100e40afe09fdd89d81bc4e162fe94f50c789be6/src/OpenSleigh.Transport.RabbitMQ/PublisherChannelContext.cs
this is taking care of disposing a channel, but I totally see your point. I was already not super satisfied with the design, I'll definitely update the code. 
Thanks!

**Comment by micdenny** [comment]
> this is taking care of disposing a channel

but I can't see where the dispose is called in the pipeline, and I don't see any using, what else I'm missing about c# 9? records are disposed in a mystic way? 😄 

> I was already not super satisfied with the design, I'll definitely update the code.

glad to help

**Comment by mizrael** [comment]
I said it's taking care of it, not that it's getting triggered :D

Il giorno ven 8 gen 2021 alle ore 11:36 Michael Denny <
notifications@github.com> ha scritto:

**Comment by mizrael** [comment]
@micdenny what do you think of this PR: https://github.com/mizrael/OpenSleigh/pull/13 ?
